### PR TITLE
Add Beancount `ctags` parser

### PR DESCRIPTION
**Pull request by aldur**

### CODE REVIEW

**Comment by siddhantgoel** [comment]
Would you like to link to the main branch (https://github.com/aldur/dotfiles/blob/master/various/ctags/beancount.ctags) instead? Or any specific reason behind linking to a specific commit?

**Comment by aldur** [comment]
I usually link to the commit so that if the directory structure changes or the file moves we don't end up with a broken link. 

The downside is that this way we don't get updates. But I don't expect this file too evolve too much. 

Happy to change it if you think it's best.

**Comment by siddhantgoel** [comment]
Let's update the link to use the branch. :)

**Comment by aldur** [comment]
Done!

**Comment by siddhantgoel** [comment]
Thanks!

**Pull request merged**
